[project]
name = "cotc-common"
version = "0.1.0"
description = "COTC common library"
requires-python = ">=3.12"
dependencies = [
    "pydantic>=2.10.6",
]

[build-system]
requires = ["hatchling"]
build-backend = "hatchling.build"
